// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDomainPayload post domain payload
//
// swagger:model postDomainPayload
type PostDomainPayload struct {

	// domain
	// Example: maps.google.com
	// Required: true
	Domain *string `json:"domain"`

	// ID of parent domain
	// Example: 891d37d3-c74f-493e-aea8-af73efd92016
	// Format: uuid4
	ParentDomainID strfmt.UUID4 `json:"parentDomainID,omitempty"`
}

// Validate validates this post domain payload
func (m *PostDomainPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentDomainID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostDomainPayload) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *PostDomainPayload) validateParentDomainID(formats strfmt.Registry) error {
	if swag.IsZero(m.ParentDomainID) { // not required
		return nil
	}

	if err := validate.FormatOf("parentDomainID", "body", "uuid4", m.ParentDomainID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post domain payload based on context it is used
func (m *PostDomainPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostDomainPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDomainPayload) UnmarshalBinary(b []byte) error {
	var res PostDomainPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
