swagger: "2.0"
info:
  title: allaboutapps.dev/aw/go-starter
  version: 0.1.0
paths:
  /swagger.yml:
    get:
      summary: Get swagger.yml
      operationId: GetSwaggerRoute
      produces:
        - text/plain
      description: |-
        OpenAPI Specification ver. 2 (fka Swagger)
        Returns our handcrafted and validated `swagger.yml`.
      tags:
        - common
      responses:
        "200":
          description: OK
  /-/ready:
    get:
      summary: Get ready
      operationId: GetReadyRoute
      produces:
        - text/plain
      description: |-
        This endpoint returns 200 when the service is ready to serve traffic (i.e. respond to queries).
      tags:
        - common
      responses:
        "200":
          description: Ready.
        "521":
          description: Not ready.
  /-/healthy:
    get:
      security:
        - Management: []
      summary: Get healthy
      operationId: GetHealthyRoute
      produces:
        - text/plain
      description: |-
        This endpoint returns 200 when the service is healthy.
        It performs additional checks to ensure other parts of the system are available.
      tags:
        - common
      responses:
        "200":
          description: Ready.
        "521":
          description: Not ready.
