swagger: "2.0"
info:
  title: stamp
  version: 0.1.0
paths:
  /api/v1/domains:
    post:
      summary: Add a domain
      security:
        - Bearer: []
      operationId: PostDomainRoute
      description: |-
        Adds a domain, if it not already exists, to be stamped.
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/domain.yml#/definitions/PostDomainPayload"
      tags:
        - domain
      responses:
        "200":
          description: PostDomainResponse
          schema:
            $ref: "../definitions/domain.yml#/definitions/Domain"