swagger: "2.0"
info:
  title: stamp
  version: 0.1.0
paths:
  /api/v1/stamp:
    post:
      summary: Stamp a domain
      security:
        - Bearer: []
      operationId: PostStampRoute
      description: |-
        Add a stamp to a domain
      parameters:
        - name: Payload
          in: body
          schema:
            $ref: "../definitions/stamp.yml#/definitions/PostStampPayload"
      tags:
        - stamp
      responses:
        "200":
          description: PostStampResponse
          schema:
            $ref: "../definitions/stamp.yml#/definitions/PostStampResponse"