// Code generated by go-swagger; DO NOT EDIT.

package stamp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewDeleteVoteRouteParams creates a new DeleteVoteRouteParams object
// no default values defined in spec.
func NewDeleteVoteRouteParams() DeleteVoteRouteParams {

	return DeleteVoteRouteParams{}
}

// DeleteVoteRouteParams contains all the bound params for the delete vote route operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteVoteRoute
type DeleteVoteRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	VoteID strfmt.UUID4 `param:"voteId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteVoteRouteParams() beforehand.
func (o *DeleteVoteRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rVoteID, rhkVoteID, _ := route.Params.GetOK("voteId")
	if err := o.bindVoteID(rVoteID, rhkVoteID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteVoteRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// voteId
	// Required: true
	// Parameter is provided by construction from the route

	if err := o.validateVoteID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVoteID binds and validates parameter VoteID from path.
func (o *DeleteVoteRouteParams) bindVoteID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid4
	value, err := formats.Parse("uuid4", raw)
	if err != nil {
		return errors.InvalidType("voteId", "path", "strfmt.UUID4", raw)
	}
	o.VoteID = *(value.(*strfmt.UUID4))

	if err := o.validateVoteID(formats); err != nil {
		return err
	}

	return nil
}

// validateVoteID carries on validations for parameter VoteID
func (o *DeleteVoteRouteParams) validateVoteID(formats strfmt.Registry) error {

	if err := validate.FormatOf("voteId", "path", "uuid4", o.VoteID.String(), formats); err != nil {
		return err
	}
	return nil
}
