// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStamps(t *testing.T) {
	t.Parallel()

	query := Stamps()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStampsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStampsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Stamps().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStampsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StampSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStampsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StampExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Stamp exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StampExists to return true, but got false.")
	}
}

func testStampsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	stampFound, err := FindStamp(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if stampFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStampsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Stamps().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStampsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Stamps().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStampsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	stampOne := &Stamp{}
	stampTwo := &Stamp{}
	if err = randomize.Struct(seed, stampOne, stampDBTypes, false, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}
	if err = randomize.Struct(seed, stampTwo, stampDBTypes, false, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stampOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stampTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Stamps().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStampsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	stampOne := &Stamp{}
	stampTwo := &Stamp{}
	if err = randomize.Struct(seed, stampOne, stampDBTypes, false, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}
	if err = randomize.Struct(seed, stampTwo, stampDBTypes, false, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = stampOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = stampTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testStampsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStampsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(stampColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStampToManyDomainStamps(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Stamp
	var b, c DomainStamp

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, domainStampDBTypes, false, domainStampColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, domainStampDBTypes, false, domainStampColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.StampID = a.ID
	c.StampID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.DomainStamps().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.StampID == b.StampID {
			bFound = true
		}
		if v.StampID == c.StampID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := StampSlice{&a}
	if err = a.L.LoadDomainStamps(ctx, tx, false, (*[]*Stamp)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DomainStamps); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.DomainStamps = nil
	if err = a.L.LoadDomainStamps(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DomainStamps); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testStampToManyAddOpDomainStamps(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Stamp
	var b, c, d, e DomainStamp

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, stampDBTypes, false, strmangle.SetComplement(stampPrimaryKeyColumns, stampColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*DomainStamp{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, domainStampDBTypes, false, strmangle.SetComplement(domainStampPrimaryKeyColumns, domainStampColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*DomainStamp{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDomainStamps(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.StampID {
			t.Error("foreign key was wrong value", a.ID, first.StampID)
		}
		if a.ID != second.StampID {
			t.Error("foreign key was wrong value", a.ID, second.StampID)
		}

		if first.R.Stamp != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Stamp != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.DomainStamps[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.DomainStamps[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.DomainStamps().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testStampsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStampsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StampSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStampsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Stamps().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	stampDBTypes = map[string]string{`ID`: `uuid`, `Name`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_            = bytes.MinRead
)

func testStampsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(stampPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(stampAllColumns) == len(stampPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stampDBTypes, true, stampPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStampsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(stampAllColumns) == len(stampPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Stamp{}
	if err = randomize.Struct(seed, o, stampDBTypes, true, stampColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, stampDBTypes, true, stampPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(stampAllColumns, stampPrimaryKeyColumns) {
		fields = stampAllColumns
	} else {
		fields = strmangle.SetComplement(
			stampAllColumns,
			stampPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StampSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStampsUpsert(t *testing.T) {
	t.Parallel()

	if len(stampAllColumns) == len(stampPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Stamp{}
	if err = randomize.Struct(seed, &o, stampDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Stamp: %s", err)
	}

	count, err := Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, stampDBTypes, false, stampPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Stamp struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Stamp: %s", err)
	}

	count, err = Stamps().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
