swagger: "2.0"
info:
  title: stamp
  version: 0.1.0
paths: {}
definitions:
  PostStampPayload:
    type: object
    required:
      - domainId
      - stampId
      - approved
    properties:
      domainId:
        type: string
        format: uuid4
        description: ID of the domain
      stampId:
        type: string
        format: uuid4
        description: ID of the stamp
      approved:
        type: boolean
        description: If the vote agrees with the stamp
      rating:
        type: integer
        minimum: 0
        maximum: 9
        description: Optional rating, only possible if the vote agrees
        x-nullable: true
  PostStampResponse:
    type: object
    required:
      - domainId
      - stampId
      - votes
    properties: 
      domainId:
        type: string
        format: uuid4
        description: ID of the domain
      stampId:
        type: string
        format: uuid4
        description: ID of the stamp
      votes:
        type: array
        items: 
          $ref: "votes.yml#/definitions/Vote"
    
